# Generated by Django 4.1.1 on 2022-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_create', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ether',
            new_name='pollachi',
        ),
    ]
