# Generated by Django 4.1.1 on 2022-09-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_create', '0002_rename_ether_pollachi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pollachi',
            new_name='ether',
        ),
    ]
